### PR TITLE
Final Changes to Edit Command and others

### LINKED ISSUE #178: [PE-D][Tester B] Error message not appropriate for delete
As shown below, when deleting a transaction, the range should be from 1 to 1000000.

Hence, 10000 which is figurative speaking valid should not be deemed as invalid as shown in the error message.

Do consider rephrasing the error message to something like "Transaction of xx index does not exist." which might be more appropriate.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: OVReader/ped#4

### LINKED ISSUE #235: [Bug] Edit command without optional tags resulted in false edit message
image

@brian-vb has observed that edit e/1 shows the user that the entry has been edited where it shouldnt be. When there are no changes (no optional tags in user input), the program should show a message like "Optional tags required for Edit operation".

Fix could be done within EditCommand.execute() where the newly stored attributes would be checked for null or 0 (for amount). If there are no newly editted attribute, an exception would be thrown.

### PR DESCRIPTION
**Pull request by brian-vb**

### CODE REVIEW

File: src/main/java/seedu/duke/command/EditCommand.java [hunk 1]
```diff
@@ -135,57 +138,73 @@ public void execute(TransactionList transactions, Ui ui, Storage storage) throws
...
+                    + "an exception later.");
+            if (check) {
+                Transaction entry = transactions.getEntry(index - 1);
+                boolean thirdCheck = isParametersChanged(entry, newType, newDescription, newAmount,
+                        newCategory, newDate);
+
+                editLogger.log(Level.INFO, "If tags are empty or the tags will result in an unedited "
+                        + "transaction, the command will stop executing and throw an exception later.");
+
+                if (secondCheck && thirdCheck) {
```
Comment (chydarren) [inline src/main/java/seedu/duke/command/EditCommand.java:157]: Might want to name this variables with semantic meanings as it isn't quite clear what are these checks. As these are Boolean variables, the naming should be like `isBoolean`, `isDone`, etc.

**Review by chydarren — APPROVED** [review]
Code looks a lot more organized! Thanks for updating these portions. Some variables might not have been named properly, might want to look into the naming but other than that, all's good. Thanks!
