### PR TITLE
Fix constants as per @dranov's comments 

### LINKED ISSUE #223: Code review for @chinhan99
# @chinhan99

- [x] Making something a constant does not mean it's no longer a [magic number](https://nus-cs2113-ay2223s1.github.io/website/se-book-adapted/chapters/codeQuality.html#avoid-magic-numbers). The constant's name should explain its meaning, not its value. `static final int THREE = 3` is still a magic number :-)

https://github.com/AY2223S1-CS2113-W12-2/tp/blob/b53a3c2bc91adbdeaaf886db361511e8925b02f1/src/main/java/seedu/duke/Storage.java#L34-L36

https://github.com/AY2223S1-CS2113-W12-2/tp/blob/b53a3c2bc91adbdeaaf886db361511e8925b02f1/src/main/java/seedu/duke/Storage.java#L207-L228

- [x] Maybe these strings could be made constants
https://github.com/AY2223S1-CS2113-W12-2/tp/blob/b53a3c2bc91adbdeaaf886db361511e8925b02f1/src/main/java/seedu/duke/Storage.java#L143

### PR DESCRIPTION
**Pull request by chinhan99**
Also added more comments, and fixed logging warnings.

### CODE REVIEW

File: src/main/java/seedu/duke/command/FindCommand.java [hunk 1]
```diff
@@ -36,13 +37,15 @@ public FindCommand(String keywords) {
...
 
+
     /**
      * Checks the format of find to ensure that it contains keywords used in the search expression.
      *
      * @param keywords A string containing the keywords used in the search expression.
      * @throws FindTransactionMissingKeywordsException If a user does not enter a search expression for Find.
      */
     public static void checkFindFormat(String keywords) throws FindTransactionMissingKeywordsException {
+        findLogger.setLevel(Level.SEVERE);
```
Comment (chydarren) [inline src/main/java/seedu/duke/command/FindCommand.java:48]: Thanks for adding this set level statement here to control the display of the severity message!

**Review by chydarren — APPROVED** [review]
Constants are better named now with clarity. Coding style is followed, no issues. Thanks!
