### PR TITLE
Fix error messages to redirect users to the help command

### LINKED ISSUE #200: [PE-D][Tester B] Adding valid input examples (maybe UG examples) to error messages (suggestion)
Do consider adding maybe UG examples to relevant error messages. For example, `delete e/1` for the wrong delete format error, etc. This will be very helpful for the user especially for long commands like `add` and `edit`.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: OVReader/ped#9

### PR DESCRIPTION
**Pull request by chinhan99**
1) Fix the error messages to direct users to use the help command for all invalid commands from user feedback. 
2) Made minor updates to the storage error message.
3) Attempt to fix gitignore , because duke.txt still gets stored in github.

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -13,6 +13,7 @@ src/main/resources/docs/
 *.iml
 bin/
 
-/data/duke.txt
+
```
Comment (chinhan99) [inline .gitignore:16]: Attempt to resolve duke.txt file being included in the commit

File: src/main/java/seedu/duke/common/ErrorMessages.java [hunk 2]
```diff
@@ -4,40 +4,48 @@
...
-            + " To preserve data, please STOP the program and edit your data file correctly."),
+            + " To PREVENT DATA OVERWRITE, please STOP the program and EDIT your duke.txt file correctly."),
     ERROR_STORAGE_WRITE("Unable to write to Duke.txt. Please save your current Duke.txt file and restart Moolah"),
     ERROR_MAXIMUM_TRANSACTION_COUNT_REACHED("Unable to add transaction. "
             + "The maximum allowed transaction size (1000000) has been reached."),
 
-    ERROR_INVALID_BUDGET("Invalid budget amount, please ensure your amount is in positive whole number"
-            + " of valid range only!"),
+    ERROR_INVALID_BUDGET("Invalid budget amount! (Note: Budget must be a positive integer of valid range)"
+            + " Please enter <help> for the command guide."),
```
Comment (wcwy) [inline src/main/java/seedu/duke/common/ErrorMessages.java:48]: Usage of integer here is not very accurate since from the programming point of view, the budget is a long instead of integer. Perhaps using whole number here will be better for the budget.
