### PR TITLE
Modify Find function to ignore case-sensitivity and compare only descriptions

### LINKED ISSUE #177: [PE-D][Tester D] Unintuitive find function
Understand that Oct 2 is formatted at Oct 02, but it's unintuitive to the user that when he is finding transactions happening on Oct 2, he gets those on Oct 27

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: dhanish265/ped#6

### LINKED ISSUE #182: [PE-D][Tester D] May want to consider insensitive-case matching for find
Users may enter find terms in all lower-case, and be disappointed when they cannot find what they're looking for

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: dhanish265/ped#7

### LINKED ISSUE #190: [PE-D][Tester A] Find at shows the whole list
Find at returns whole list of expense and income.
(Same issue for find [ , ], | , : , (any substring of description) )

Steps to reproduce:
- run " add t/expense c/leisure a/1 d/02102022 i/used_at_outings "
- run " add t/expense c/transport a/1 d/02102022 i/bus_fare "
- run " find at "

expected output:
[-][leisure] $1 at Oct 02 2022 | Description: used_at_outings

actual output:

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: LokQiJun/ped#5

### PR DESCRIPTION
**Pull request by chydarren**
This pull request seeks to modify the Find function to ignore case-sensitivity, and compare only the description field in each transaction. As for the filtering for other types of tags, the user may use the `list` function instead which comes with tag filters. This way, the Find function will be more apt for its purpose and interaction is also more intuitive.

This PR will address the suggestions highlighted in: https://github.com/AY2223S1-CS2113-W12-2/tp/issues/182 and https://github.com/AY2223S1-CS2113-W12-2/tp/issues/177.

### CODE REVIEW

File: src/main/java/seedu/duke/data/TransactionList.java [hunk 1]
```diff
@@ -235,7 +235,7 @@ public String findTransactions(String keywords) {
         // Loops each transaction from the transactions list
         for (Transaction transaction : transactions) {
             // Includes only transactions that contain the keywords used in the search expression
-            if (transaction.toString().contains(keywords)) {
+            if (transaction.getDescription().toLowerCase().contains(keywords.toLowerCase())) {
```
Comment (wcwy) [inline src/main/java/seedu/duke/data/TransactionList.java:238]: Cool! One line changed and two issues solved! Don't forget to update the help command, ug and potentially dg on the new change.

**Review by wcwy — APPROVED** [review]

File: src/main/java/seedu/duke/data/TransactionList.java (hunk 1 above)
Comment (chydarren) [reply src/main/java/seedu/duke/data/TransactionList.java:238]: Thank you and noted!!
